2023-06-08 13:41:43.974 | ERROR    | handlers.errors:errors_handler:11 - Error binding parameter 0 - probably unsupported type.
Traceback (most recent call last):

  File "D:\Telegram Apps\aiobot\app.py", line 28, in <module>
    executor.start_polling(
    │        └ <function start_polling at 0x00000235E45A08B0>
    └ <module 'aiogram.utils.executor' from 'C:\\Users\\ADMIN\\.virtualenvs\\aiobot-Mkxe9VKQ\\lib\\site-packages\\aiogram\\utils\\e...

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\utils\executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x00000235E45A12D0>
    └ <aiogram.utils.executor.Executor object at 0x00000235E16BD0C0>

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\utils\executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x00000235E34A1AB0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x00000235E33EAA70>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x00000235E3341FC0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 197355958, "message": {"message_id": 26579, "from": {"id": 5688885462, "is_bot": false, "first_name": ...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000235E4E50EE0>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

> File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x00000235E426D090>
                 │    │                │      └ <Update {"update_id": 197355958, "message": {"message_id": 26579, "from": {"id": 5688885462, "is_bot": false, "first_name": "...
                 │    │                └ <function Handler.notify at 0x00000235E448B880>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x00000235E4E513F0>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x00000235E4E50EE0>

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 26579, "from": {"id": 5688885462, "is_bot": false, "first_name": "ds_code", "username": "pycyberuz",...
                     │           └ <function start_bot_command at 0x00000235E4F30700>
                     └ Handler.HandlerObj(handler=<function start_bot_command at 0x00000235E4F30700>, spec=FullArgSpec(args=['message'], varargs=Non...

  File "D:\Telegram Apps\aiobot\handlers\users\start_user.py", line 9, in start_bot_command
    db.add_user(user_id, message.from_user.language_code)
    │  │        │        │       └ <aiogram.types.fields.Field object at 0x00000235E4213C40>
    │  │        │        └ <Message {"message_id": 26579, "from": {"id": 5688885462, "is_bot": false, "first_name": "ds_code", "username": "pycyberuz", ...
    │  │        └ 5688885462
    │  └ <function Database.add_user at 0x00000235E4E49EA0>
    └ <utils_bot.database_controller.Database object at 0x00000235E4E52050>

  File "D:\Telegram Apps\aiobot\utils_bot\database_controller.py", line 50, in add_user
    self.execute(sql, parameters=(id, user_language), commit=True)
    │    │       │                    └ 'en'
    │    │       └ '\n        INSERT INTO Users(user_id, user_language) VALUES(?, ?)\n        '
    │    └ <function Database.execute at 0x00000235E4E49CF0>
    └ <utils_bot.database_controller.Database object at 0x00000235E4E52050>

  File "D:\Telegram Apps\aiobot\utils_bot\database_controller.py", line 18, in execute
    cursor.execute(sql, parameters)
    │      │       │    └ (<built-in function id>, 'en')
    │      │       └ '\n        INSERT INTO Users(user_id, user_language) VALUES(?, ?)\n        '
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x00000235E4E86940>

sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
2023-06-08 13:41:44.144 | DEBUG    | handlers.errors:errors_handler:12 - {"update_id": 197355958, "message": {"message_id": 26579, "from": {"id": 5688885462, "is_bot": false, "first_name": "ds_code", "username": "pycyberuz", "language_code": "en"}, "chat": {"id": 5688885462, "first_name": "ds_code", "username": "pycyberuz", "type": "private"}, "date": 1686231702, "text": "/start", "entities": [{"type": "bot_command", "offset": 0, "length": 6}]}}
2023-06-08 13:43:36.956 | INFO     | __main__:on_shutdown:21 - This bot succesfully stopped!
2023-06-08 13:43:59.190 | ERROR    | handlers.errors:errors_handler:11 - Error binding parameter 0 - probably unsupported type.
Traceback (most recent call last):

  File "D:\Telegram Apps\aiobot\app.py", line 28, in <module>
    executor.start_polling(
    │        └ <function start_polling at 0x000002A9A4A808B0>
    └ <module 'aiogram.utils.executor' from 'C:\\Users\\ADMIN\\.virtualenvs\\aiobot-Mkxe9VKQ\\lib\\site-packages\\aiogram\\utils\\e...

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\utils\executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x000002A9A4A812D0>
    └ <aiogram.utils.executor.Executor object at 0x000002A9A1BED0C0>

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\utils\executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000002A9A3911AB0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000002A9A384AA70>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000002A9A37A1FC0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 197355959, "message": {"message_id": 26584, "from": {"id": 5688885462, "is_bot": false, "first_name": ...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000002A9A5347A90>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

> File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x000002A9A474D090>
                 │    │                │      └ <Update {"update_id": 197355959, "message": {"message_id": 26584, "from": {"id": 5688885462, "is_bot": false, "first_name": "...
                 │    │                └ <function Handler.notify at 0x000002A9A496B880>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x000002A9A5347FA0>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x000002A9A5347A90>

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 26584, "from": {"id": 5688885462, "is_bot": false, "first_name": "ds_code", "username": "pycyberuz",...
                     │           └ <function start_bot_command at 0x000002A9A5410700>
                     └ Handler.HandlerObj(handler=<function start_bot_command at 0x000002A9A5410700>, spec=FullArgSpec(args=['message'], varargs=Non...

  File "D:\Telegram Apps\aiobot\handlers\users\start_user.py", line 9, in start_bot_command
    db.add_user(user_id, message.from_user.language_code)
    │  │        │        │       └ <aiogram.types.fields.Field object at 0x000002A9A46F3C40>
    │  │        │        └ <Message {"message_id": 26584, "from": {"id": 5688885462, "is_bot": false, "first_name": "ds_code", "username": "pycyberuz", ...
    │  │        └ 5688885462
    │  └ <function Database.add_user at 0x000002A9A5329EA0>
    └ <utils_bot.database_controller.Database object at 0x000002A9A5346440>

  File "D:\Telegram Apps\aiobot\utils_bot\database_controller.py", line 50, in add_user
    self.execute(sql, parameters=(id, user_language), commit=True)
    │    │       │                    └ 'en'
    │    │       └ '\n        INSERT INTO Users(user_id, user_language) VALUES(?, ?)\n        '
    │    └ <function Database.execute at 0x000002A9A5329CF0>
    └ <utils_bot.database_controller.Database object at 0x000002A9A5346440>

  File "D:\Telegram Apps\aiobot\utils_bot\database_controller.py", line 18, in execute
    cursor.execute(sql, parameters)
    │      │       │    └ (<built-in function id>, 'en')
    │      │       └ '\n        INSERT INTO Users(user_id, user_language) VALUES(?, ?)\n        '
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x000002A9A536A940>

sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
2023-06-08 13:43:59.209 | DEBUG    | handlers.errors:errors_handler:12 - {"update_id": 197355959, "message": {"message_id": 26584, "from": {"id": 5688885462, "is_bot": false, "first_name": "ds_code", "username": "pycyberuz", "language_code": "en"}, "chat": {"id": 5688885462, "first_name": "ds_code", "username": "pycyberuz", "type": "private"}, "date": 1686231838, "text": "/start", "entities": [{"type": "bot_command", "offset": 0, "length": 6}]}}
2023-06-08 13:44:04.704 | INFO     | __main__:on_shutdown:21 - This bot succesfully stopped!
2023-06-08 13:44:13.668 | ERROR    | handlers.errors:errors_handler:11 - Error binding parameter 0 - probably unsupported type.
Traceback (most recent call last):

  File "D:\Telegram Apps\aiobot\app.py", line 28, in <module>
    executor.start_polling(
    │        └ <function start_polling at 0x0000021FE4E408B0>
    └ <module 'aiogram.utils.executor' from 'C:\\Users\\ADMIN\\.virtualenvs\\aiobot-Mkxe9VKQ\\lib\\site-packages\\aiogram\\utils\\e...

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\utils\executor.py", line 45, in start_polling
    executor.start_polling(
    │        └ <function Executor.start_polling at 0x0000021FE4E412D0>
    └ <aiogram.utils.executor.Executor object at 0x0000021FE202D0C0>

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\utils\executor.py", line 323, in start_polling
    loop.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x0000021FE3D11AB0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x0000021FE3C5AA70>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x0000021FE3BB1FC0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Update {"update_id": 197355960, "message": {"message_id": 26589, "from": {"id": 5688885462, "is_bot": false, "first_name": ...
                     │           └ <bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000021FE5700DF0>>
                     └ Handler.HandlerObj(handler=<bound method Dispatcher.process_update of <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0...

> File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
                 │    │                │      │      └ <aiogram.types.fields.Field object at 0x0000021FE4B0CFA0>
                 │    │                │      └ <Update {"update_id": 197355960, "message": {"message_id": 26589, "from": {"id": 5688885462, "is_bot": false, "first_name": "...
                 │    │                └ <function Handler.notify at 0x0000021FE4D2B880>
                 │    └ <aiogram.dispatcher.handler.Handler object at 0x0000021FE5701300>
                 └ <aiogram.dispatcher.dispatcher.Dispatcher object at 0x0000021FE5700DF0>

  File "C:\Users\ADMIN\.virtualenvs\aiobot-Mkxe9VKQ\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
                     │           │        │       └ {}
                     │           │        └ (<Message {"message_id": 26589, "from": {"id": 5688885462, "is_bot": false, "first_name": "ds_code", "username": "pycyberuz",...
                     │           └ <function start_bot_command at 0x0000021FE57D0700>
                     └ Handler.HandlerObj(handler=<function start_bot_command at 0x0000021FE57D0700>, spec=FullArgSpec(args=['message'], varargs=Non...

  File "D:\Telegram Apps\aiobot\handlers\users\start_user.py", line 9, in start_bot_command
    db.add_user(user_id, message.from_user.language_code)
    │  │        │        │       └ <aiogram.types.fields.Field object at 0x0000021FE4AB3B50>
    │  │        │        └ <Message {"message_id": 26589, "from": {"id": 5688885462, "is_bot": false, "first_name": "ds_code", "username": "pycyberuz", ...
    │  │        └ 5688885462
    │  └ <function Database.add_user at 0x0000021FE56E9EA0>
    └ <utils_bot.database_controller.Database object at 0x0000021FE5701F60>

  File "D:\Telegram Apps\aiobot\utils_bot\database_controller.py", line 50, in add_user
    self.execute(sql, parameters=(id, user_language), commit=True)
    │    │       │                    └ 'en'
    │    │       └ '\n        INSERT INTO Users(user_id, user_language) VALUES(?, ?)\n        '
    │    └ <function Database.execute at 0x0000021FE56E9CF0>
    └ <utils_bot.database_controller.Database object at 0x0000021FE5701F60>

  File "D:\Telegram Apps\aiobot\utils_bot\database_controller.py", line 18, in execute
    cursor.execute(sql, parameters)
    │      │       │    └ (<built-in function id>, 'en')
    │      │       └ '\n        INSERT INTO Users(user_id, user_language) VALUES(?, ?)\n        '
    │      └ <method 'execute' of 'sqlite3.Cursor' objects>
    └ <sqlite3.Cursor object at 0x0000021FE5726940>

sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
2023-06-08 13:44:13.686 | DEBUG    | handlers.errors:errors_handler:12 - {"update_id": 197355960, "message": {"message_id": 26589, "from": {"id": 5688885462, "is_bot": false, "first_name": "ds_code", "username": "pycyberuz", "language_code": "en"}, "chat": {"id": 5688885462, "first_name": "ds_code", "username": "pycyberuz", "type": "private"}, "date": 1686231852, "text": "/start", "entities": [{"type": "bot_command", "offset": 0, "length": 6}]}}
2023-06-08 13:44:29.100 | INFO     | __main__:on_shutdown:21 - This bot succesfully stopped!
